ANIME_TITLE_XPATH = '/html/body/div[3]/div/div[2]/div/div[2]/text()'
ANIME_DISPLAY_STATUS_XPATH = '/html/body/div[3]/div/div[2]/div/div[5]/div[3]/text()'
ANIME_COVER_XPATH = '/html/body/div[4]/div/div[2]/div[1]/a/div/img'
ANIME_SEASONS_XPATH_V1 = '/html/body/div[4]/div/div[2]/div[{}]/a'
ANIME_SEASONS_XPATH_V2 = '/html/body/div[4]/div/div[3]/div[{}]/a'
ANIME_EPISODE_INFORMATIONS_URL = 'https://saikoanimes.net/baixar/?={}'
EPISODES_XPATH = '/html/body/div[3]/div/div[4]/nav[*]'
REGEX_REMOVE_SPECIAL_CHARACTERS = '[^A-Za-z0-9]'
REGEX_REMOVE_LAST_SPACE_AND_TABULATION = '[ \t]+$'
